[package]
name = "suanleme-macro"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true

[lib]
proc-macro = true

[dependencies]
quote = "1.0.36"
syn = { version = "2.0.66", features = ["full"] }
proc-macro2 = "1.0.85"
