[package]
name = "suanleme-common"
version = "0.1.49"
authors.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true

[dependencies]
suanleme-macro.workspace = true
suanleme-derive-macro.workspace = true
fusen-rs = "0.6.14"

#网络协议处理
tokio = { version = "1.41.1", features = ["full"] }
bytes = "1.8.0"

#json序列化
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
serde_yaml = "0.9.34"

#nacos配置中心
nacos-sdk = { version = "0.4.2", features = ["default"] }

#日志处理
tracing = "0.1.40"
tracing-futures = { version = "0.2.5" }
tracing-subscriber = { version = "0.3.18", features = [
    "json",
    "env-filter",
    "local-time",
] }
pretty_env_logger = "0.5.0"
tracing-appender = "0.2.3"
tracing-opentelemetry = "0.28.0"
opentelemetry = "0.27.1"
opentelemetry_sdk = { version = "0.27.1", features = ["rt-tokio"] }
opentelemetry-otlp = "0.27.0"

#其他
lazy_static = "1.5.0"
toml = "0.8.19"
uuid = { version = "1.11.0", features = ["v4"] }

#时间
chrono = "0.4.38"

#redis
redis = { version = "0.27.5", features = [
    "tokio-comp",
    "connection-manager",
    "keep-alive",
] }
r2d2 = "0.8.10"

#加解密
rsa = "0.9.6"
sha2 = { version = "0.10.8", features = ["oid"] }
rand = "0.8.5"
base64 = "0.22.1"
ring = "0.17.8"
