pub mod config;
pub mod datasource;
pub mod error;
pub mod log;
pub mod nacos;
pub mod redis;
pub mod shutdown;
pub mod support;
pub mod utils;
pub mod business;
pub use nacos_sdk;
pub use sqlx;
pub type FusenFuture<T> = std::pin::Pin<Box<dyn std::future::Future<Output = T> + Send>>;
