[workspace]
members = ["suanleme-common", "suanleme-macro"]
resolver = "2"

[workspace.package]
authors = ["kwsc98 <kwsc98@gmail.com>"]
version = "0.0.34"
edition = "2021"
license = "Apache-2.0"
description = "suanleme common module"

[workspace.dependencies]
suanleme-macro = { path = "suanleme-macro", version = "0.0.34", registry = "suanleme" }
suanleme-common = { path = "suanleme-common", version = "0.0.34", registry = "suanleme" }
